# -*- coding: utf-8 -*-
"""Stock Price Pridiction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jBHhYqI_MODPLl92_ovixZLiFJICp-ud
"""

import numpy as np
import pandas as pd
import os
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

df_stock = pd.read_csv('/content/infolimpioavanzadoTarget.csv')
df_stock.head()

df_stock.tail(5)

df_stock.shape

df_stock.info()

df_stock.describe()

df_stock.isnull()

df_stock.isnull().sum()

data_new = df_stock[['date','open', 'high', 'low', 'close']]
data_new

data_new.isnull()

data_new.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt
data_new["tomorrow"]= data_new["close"].shift(-1)
data_new

data_new["target"] = data_new["tomorrow"] > data_new["close"].astype(float)
data_new

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=200, min_samples_split= 100, random_state=1)
train = data_new.iloc[:-100]
test = data_new.iloc[-100:]
predictors = ["open", "high", "low", "close"]
model.fit(train[predictors], train["target"])

from sklearn.metrics import precision_score
pred = model.predict(test[predictors])
pred

pred=pred/100
pred

pred_series = pd.Series(pred)
pred_counts = pred_series.value_counts()
print(pred_counts)